version: '3.8'

services:
  hoanglinh-medicine:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key
      - OPENAI_API_KEY=your-openai-api-key
      - STRIPE_SECRET_KEY=your-stripe-secret-key
      - STRIPE_PUBLISHABLE_KEY=your-stripe-publishable-key
    restart: unless-stopped
    networks:
      - hoanglinh-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - hoanglinh-medicine
    restart: unless-stopped
    networks:
      - hoanglinh-network

networks:
  hoanglinh-network:
    driver: bridge 