services:
  # Web Frontend (Next.js)
  - type: web
    name: hoanglinhmedicine-web
    env: node
    plan: starter
    buildCommand: cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: "AIzaSyDug_NyDb_oVP_Pl5yXSFcy72dq7PjCYhY"
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: "hoanglinh-obesity-care.firebaseapp.com"
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: "hoanglinh-obesity-care"
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: "hoanglinh-obesity-care.firebasestorage.app"
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "860032582221"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: "1:860032582221:web:e3c5923cbe504725d91204"
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        value: "G-T9Z1DMXE8P"
      - key: PORT
        value: "3000"
    healthCheckPath: /
    autoDeploy: true
    branch: main

  # API Backend (NestJS)
  - type: web
    name: hoanglinhmedicine-api
    env: node
    plan: starter
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_API_KEY
        value: "AIzaSyDug_NyDb_oVP_Pl5yXSFcy72dq7PjCYhY"
      - key: FIREBASE_AUTH_DOMAIN
        value: "hoanglinh-obesity-care.firebaseapp.com"
      - key: FIREBASE_PROJECT_ID
        value: "hoanglinh-obesity-care"
      - key: FIREBASE_STORAGE_BUCKET
        value: "hoanglinh-obesity-care.firebasestorage.app"
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "860032582221"
      - key: FIREBASE_APP_ID
        value: "1:860032582221:web:e3c5923cbe504725d91204"
      - key: FIREBASE_MEASUREMENT_ID
        value: "G-T9Z1DMXE8P"
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
    healthCheckPath: /health
    autoDeploy: true
    branch: main

# No external databases needed - using Firebase Firestore