services:
  # Web Frontend (Next.js)
  - type: web
    name: hoanglinhmedicine-web
    env: node
    plan: starter
    buildCommand: npm run render:build
    startCommand: npm run render:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        fromDatabase:
          name: firebase-config
          property: apiKey
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        fromDatabase:
          name: firebase-config
          property: authDomain
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        fromDatabase:
          name: firebase-config
          property: projectId
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        fromDatabase:
          name: firebase-config
          property: storageBucket
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        fromDatabase:
          name: firebase-config
          property: messagingSenderId
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        fromDatabase:
          name: firebase-config
          property: appId
    healthCheckPath: /
    autoDeploy: true
    branch: main

  # API Backend (NestJS)
  - type: web
    name: hoanglinhmedicine-api
    env: node
    plan: starter
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_API_KEY
        fromDatabase:
          name: firebase-config
          property: apiKey
      - key: FIREBASE_AUTH_DOMAIN
        fromDatabase:
          name: firebase-config
          property: authDomain
      - key: FIREBASE_PROJECT_ID
        fromDatabase:
          name: firebase-config
          property: projectId
      - key: FIREBASE_STORAGE_BUCKET
        fromDatabase:
          name: firebase-config
          property: storageBucket
      - key: FIREBASE_MESSAGING_SENDER_ID
        fromDatabase:
          name: firebase-config
          property: messagingSenderId
      - key: FIREBASE_APP_ID
        fromDatabase:
          name: firebase-config
          property: appId
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
    healthCheckPath: /health
    autoDeploy: true
    branch: main

databases:
  - name: firebase-config
    plan: starter
    databaseName: firebase_config
    user: firebase_config_user