// Database sản phẩm mở rộng với thông tin chi tiết
export const productsDB = [
  {
    id: '1',
    name: 'Paracetamol',
    ingredient: 'Paracetamol 500mg',
    activeIngredient: 'Paracetamol',
    dosage: '500mg',
    uses: 'Giảm đau, hạ sốt',
    symptoms: ['đau đầu', 'đau răng', 'đau cơ', 'sốt', 'cảm lạnh'],
    price: 15000,
    manufacturer: 'Dược phẩm Hà Nội',
    sideEffects: ['Buồn nôn', 'Đau dạ dày'],
    instructions: 'Uống 1-2 viên mỗi 4-6 giờ khi cần thiết'
  },
  {
    id: '2',
    name: 'Vitamin C',
    ingredient: 'Vitamin C 1000mg',
    activeIngredient: 'Ascorbic Acid',
    dosage: '1000mg',
    uses: 'Tăng sức đề kháng, bổ sung vitamin C',
    symptoms: ['thiếu vitamin C', 'suy nhược', 'cảm lạnh', 'mệt mỏi'],
    price: 35000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Tiêu chảy nhẹ nếu dùng quá liều'],
    instructions: 'Uống 1 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '3',
    name: 'Ibuprofen',
    ingredient: 'Ibuprofen 400mg',
    activeIngredient: 'Ibuprofen',
    dosage: '400mg',
    uses: 'Giảm đau, chống viêm',
    symptoms: ['đau khớp', 'đau lưng', 'viêm khớp', 'đau cơ'],
    price: 25000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Đau dạ dày', 'Chóng mặt'],
    instructions: 'Uống 1 viên mỗi 6-8 giờ khi cần thiết'
  },
  {
    id: '4',
    name: 'Omeprazole',
    ingredient: 'Omeprazole 20mg',
    activeIngredient: 'Omeprazole',
    dosage: '20mg',
    uses: 'Điều trị viêm loét dạ dày, trào ngược axit',
    symptoms: ['đau dạ dày', 'ợ chua', 'trào ngược', 'viêm loét'],
    price: 45000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày trước bữa sáng'
  },
  {
    id: '5',
    name: 'Amoxicillin',
    ingredient: 'Amoxicillin 500mg',
    activeIngredient: 'Amoxicillin',
    dosage: '500mg',
    uses: 'Kháng sinh điều trị nhiễm khuẩn',
    symptoms: ['viêm họng', 'viêm phổi', 'viêm tai giữa', 'nhiễm khuẩn đường hô hấp'],
    price: 55000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Tiêu chảy', 'Buồn nôn', 'Phát ban'],
    instructions: 'Uống 1 viên 3 lần/ngày sau bữa ăn, cần đơn thuốc'
  },
  {
    id: '6',
    name: 'Cetirizine',
    ingredient: 'Cetirizine 10mg',
    activeIngredient: 'Cetirizine',
    dosage: '10mg',
    uses: 'Điều trị dị ứng, mề đay',
    symptoms: ['dị ứng', 'mề đay', 'ngứa', 'chảy nước mũi', 'hắt hơi'],
    price: 28000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Buồn ngủ', 'Khô miệng'],
    instructions: 'Uống 1 viên mỗi ngày vào buổi tối'
  },
  {
    id: '7',
    name: 'Loratadine',
    ingredient: 'Loratadine 10mg',
    activeIngredient: 'Loratadine',
    dosage: '10mg',
    uses: 'Điều trị dị ứng, không gây buồn ngủ',
    symptoms: ['dị ứng', 'viêm mũi dị ứng', 'mề đay', 'ngứa'],
    price: 32000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Đau đầu', 'Khô miệng'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '8',
    name: 'Metformin',
    ingredient: 'Metformin 500mg',
    activeIngredient: 'Metformin',
    dosage: '500mg',
    uses: 'Điều trị tiểu đường type 2',
    symptoms: ['tiểu đường', 'đái tháo đường', 'tăng đường huyết'],
    price: 85000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Tiêu chảy', 'Đau bụng'],
    instructions: 'Uống 1 viên 2-3 lần/ngày sau bữa ăn, cần đơn thuốc'
  },
  {
    id: '9',
    name: 'Losartan',
    ingredient: 'Losartan 50mg',
    activeIngredient: 'Losartan',
    dosage: '50mg',
    uses: 'Điều trị tăng huyết áp',
    symptoms: ['tăng huyết áp', 'cao huyết áp', 'huyết áp cao'],
    price: 95000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chóng mặt', 'Mệt mỏi', 'Ho khan'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '10',
    name: 'Amlodipine',
    ingredient: 'Amlodipine 5mg',
    activeIngredient: 'Amlodipine',
    dosage: '5mg',
    uses: 'Điều trị tăng huyết áp, đau thắt ngực',
    symptoms: ['tăng huyết áp', 'đau thắt ngực', 'huyết áp cao'],
    price: 78000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Phù chân', 'Chóng mặt', 'Đau đầu'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '11',
    name: 'Atorvastatin',
    ingredient: 'Atorvastatin 20mg',
    activeIngredient: 'Atorvastatin',
    dosage: '20mg',
    uses: 'Giảm cholesterol, phòng ngừa bệnh tim mạch',
    symptoms: ['cholesterol cao', 'mỡ máu cao', 'bệnh tim mạch'],
    price: 120000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau cơ', 'Buồn nôn', 'Đau đầu'],
    instructions: 'Uống 1 viên mỗi ngày vào buổi tối, cần đơn thuốc'
  },
  {
    id: '12',
    name: 'Aspirin',
    ingredient: 'Aspirin 100mg',
    activeIngredient: 'Acetylsalicylic Acid',
    dosage: '100mg',
    uses: 'Giảm đau, hạ sốt, chống đông máu',
    symptoms: ['đau đầu', 'sốt', 'đau cơ', 'phòng ngừa đột quỵ'],
    price: 18000,
    manufacturer: 'Dược phẩm Hà Nội',
    sideEffects: ['Đau dạ dày', 'Chảy máu', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '13',
    name: 'Diclofenac',
    ingredient: 'Diclofenac 50mg',
    activeIngredient: 'Diclofenac',
    dosage: '50mg',
    uses: 'Giảm đau, chống viêm',
    symptoms: ['đau khớp', 'viêm khớp', 'đau lưng', 'đau cơ'],
    price: 42000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Đau dạ dày', 'Chóng mặt', 'Buồn nôn'],
    instructions: 'Uống 1 viên 2-3 lần/ngày sau bữa ăn'
  },
  {
    id: '14',
    name: 'Ranitidine',
    ingredient: 'Ranitidine 150mg',
    activeIngredient: 'Ranitidine',
    dosage: '150mg',
    uses: 'Điều trị viêm loét dạ dày, trào ngược axit',
    symptoms: ['đau dạ dày', 'ợ chua', 'trào ngược', 'viêm loét'],
    price: 38000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Đau đầu', 'Buồn nôn', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày trước bữa ăn'
  },
  {
    id: '15',
    name: 'Ciprofloxacin',
    ingredient: 'Ciprofloxacin 500mg',
    activeIngredient: 'Ciprofloxacin',
    dosage: '500mg',
    uses: 'Kháng sinh điều trị nhiễm khuẩn',
    symptoms: ['viêm đường tiết niệu', 'viêm phổi', 'nhiễm khuẩn đường tiêu hóa'],
    price: 65000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Tiêu chảy', 'Buồn nôn', 'Chóng mặt'],
    instructions: 'Uống 1 viên 2 lần/ngày, cần đơn thuốc'
  },
  {
    id: '16',
    name: 'Azithromycin',
    ingredient: 'Azithromycin 500mg',
    activeIngredient: 'Azithromycin',
    dosage: '500mg',
    uses: 'Kháng sinh điều trị nhiễm khuẩn đường hô hấp',
    symptoms: ['viêm họng', 'viêm phổi', 'viêm xoang', 'viêm tai giữa'],
    price: 72000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Tiêu chảy', 'Buồn nôn', 'Đau bụng'],
    instructions: 'Uống 1 viên mỗi ngày trong 3-5 ngày, cần đơn thuốc'
  },
  {
    id: '17',
    name: 'Fexofenadine',
    ingredient: 'Fexofenadine 180mg',
    activeIngredient: 'Fexofenadine',
    dosage: '180mg',
    uses: 'Điều trị dị ứng, không gây buồn ngủ',
    symptoms: ['dị ứng', 'viêm mũi dị ứng', 'mề đay', 'ngứa'],
    price: 45000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau đầu', 'Buồn nôn', 'Mệt mỏi'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '18',
    name: 'Montelukast',
    ingredient: 'Montelukast 10mg',
    activeIngredient: 'Montelukast',
    dosage: '10mg',
    uses: 'Điều trị hen suyễn, viêm mũi dị ứng',
    symptoms: ['hen suyễn', 'viêm mũi dị ứng', 'ho do dị ứng'],
    price: 88000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau đầu', 'Chóng mặt', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày vào buổi tối'
  },
  {
    id: '19',
    name: 'Pantoprazole',
    ingredient: 'Pantoprazole 40mg',
    activeIngredient: 'Pantoprazole',
    dosage: '40mg',
    uses: 'Điều trị viêm loét dạ dày, trào ngược axit',
    symptoms: ['đau dạ dày', 'ợ chua', 'trào ngược', 'viêm loét'],
    price: 68000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau đầu', 'Buồn nôn', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày trước bữa sáng'
  },
  {
    id: '20',
    name: 'Esomeprazole',
    ingredient: 'Esomeprazole 20mg',
    activeIngredient: 'Esomeprazole',
    dosage: '20mg',
    uses: 'Điều trị viêm loét dạ dày, trào ngược axit',
    symptoms: ['đau dạ dày', 'ợ chua', 'trào ngược', 'viêm loét'],
    price: 75000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau đầu', 'Buồn nôn', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày trước bữa sáng'
  },
  {
    id: '21',
    name: 'Simvastatin',
    ingredient: 'Simvastatin 20mg',
    activeIngredient: 'Simvastatin',
    dosage: '20mg',
    uses: 'Giảm cholesterol, phòng ngừa bệnh tim mạch',
    symptoms: ['cholesterol cao', 'mỡ máu cao', 'bệnh tim mạch'],
    price: 95000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau cơ', 'Buồn nôn', 'Đau đầu'],
    instructions: 'Uống 1 viên mỗi ngày vào buổi tối, cần đơn thuốc'
  },
  {
    id: '22',
    name: 'Gliclazide',
    ingredient: 'Gliclazide 80mg',
    activeIngredient: 'Gliclazide',
    dosage: '80mg',
    uses: 'Điều trị tiểu đường type 2',
    symptoms: ['tiểu đường', 'đái tháo đường', 'tăng đường huyết'],
    price: 68000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Hạ đường huyết', 'Buồn nôn', 'Đau bụng'],
    instructions: 'Uống 1 viên 2 lần/ngày trước bữa ăn, cần đơn thuốc'
  },
  {
    id: '23',
    name: 'Glimepiride',
    ingredient: 'Glimepiride 1mg',
    activeIngredient: 'Glimepiride',
    dosage: '1mg',
    uses: 'Điều trị tiểu đường type 2',
    symptoms: ['tiểu đường', 'đái tháo đường', 'tăng đường huyết'],
    price: 72000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Hạ đường huyết', 'Buồn nôn', 'Đau đầu'],
    instructions: 'Uống 1 viên mỗi ngày trước bữa sáng, cần đơn thuốc'
  },
  {
    id: '24',
    name: 'Enalapril',
    ingredient: 'Enalapril 10mg',
    activeIngredient: 'Enalapril',
    dosage: '10mg',
    uses: 'Điều trị tăng huyết áp, suy tim',
    symptoms: ['tăng huyết áp', 'suy tim', 'huyết áp cao'],
    price: 85000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Ho khan', 'Chóng mặt', 'Mệt mỏi'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '25',
    name: 'Lisinopril',
    ingredient: 'Lisinopril 10mg',
    activeIngredient: 'Lisinopril',
    dosage: '10mg',
    uses: 'Điều trị tăng huyết áp, suy tim',
    symptoms: ['tăng huyết áp', 'suy tim', 'huyết áp cao'],
    price: 78000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Ho khan', 'Chóng mặt', 'Mệt mỏi'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '26',
    name: 'Bisoprolol',
    ingredient: 'Bisoprolol 5mg',
    activeIngredient: 'Bisoprolol',
    dosage: '5mg',
    uses: 'Điều trị tăng huyết áp, suy tim, đau thắt ngực',
    symptoms: ['tăng huyết áp', 'suy tim', 'đau thắt ngực'],
    price: 65000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Mệt mỏi', 'Chóng mặt', 'Nhịp tim chậm'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '27',
    name: 'Carvedilol',
    ingredient: 'Carvedilol 25mg',
    activeIngredient: 'Carvedilol',
    dosage: '25mg',
    uses: 'Điều trị tăng huyết áp, suy tim',
    symptoms: ['tăng huyết áp', 'suy tim', 'huyết áp cao'],
    price: 88000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Mệt mỏi', 'Chóng mặt', 'Buồn nôn'],
    instructions: 'Uống 1 viên 2 lần/ngày, cần đơn thuốc'
  },
  {
    id: '28',
    name: 'Nifedipine',
    ingredient: 'Nifedipine 30mg',
    activeIngredient: 'Nifedipine',
    dosage: '30mg',
    uses: 'Điều trị tăng huyết áp, đau thắt ngực',
    symptoms: ['tăng huyết áp', 'đau thắt ngực', 'huyết áp cao'],
    price: 55000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Phù chân', 'Chóng mặt', 'Đau đầu'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '29',
    name: 'Diltiazem',
    ingredient: 'Diltiazem 90mg',
    activeIngredient: 'Diltiazem',
    dosage: '90mg',
    uses: 'Điều trị tăng huyết áp, đau thắt ngực',
    symptoms: ['tăng huyết áp', 'đau thắt ngực', 'huyết áp cao'],
    price: 68000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chóng mặt', 'Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên 2 lần/ngày, cần đơn thuốc'
  },
  {
    id: '30',
    name: 'Verapamil',
    ingredient: 'Verapamil 80mg',
    activeIngredient: 'Verapamil',
    dosage: '80mg',
    uses: 'Điều trị tăng huyết áp, đau thắt ngực',
    symptoms: ['tăng huyết áp', 'đau thắt ngực', 'huyết áp cao'],
    price: 72000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chóng mặt', 'Đau đầu', 'Táo bón'],
    instructions: 'Uống 1 viên 3 lần/ngày, cần đơn thuốc'
  },
  {
    id: '31',
    name: 'Hydrochlorothiazide',
    ingredient: 'Hydrochlorothiazide 25mg',
    activeIngredient: 'Hydrochlorothiazide',
    dosage: '25mg',
    uses: 'Điều trị tăng huyết áp, phù nề',
    symptoms: ['tăng huyết áp', 'phù nề', 'huyết áp cao'],
    price: 42000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Tiểu nhiều', 'Chóng mặt', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày vào buổi sáng, cần đơn thuốc'
  },
  {
    id: '32',
    name: 'Furosemide',
    ingredient: 'Furosemide 40mg',
    activeIngredient: 'Furosemide',
    dosage: '40mg',
    uses: 'Lợi tiểu, điều trị phù nề, suy tim',
    symptoms: ['phù nề', 'suy tim', 'tăng huyết áp'],
    price: 38000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Tiểu nhiều', 'Chóng mặt', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày vào buổi sáng, cần đơn thuốc'
  },
  {
    id: '33',
    name: 'Spironolactone',
    ingredient: 'Spironolactone 25mg',
    activeIngredient: 'Spironolactone',
    dosage: '25mg',
    uses: 'Lợi tiểu, điều trị phù nề, suy tim',
    symptoms: ['phù nề', 'suy tim', 'tăng huyết áp'],
    price: 45000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Tiểu nhiều', 'Rối loạn kinh nguyệt', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '34',
    name: 'Warfarin',
    ingredient: 'Warfarin 5mg',
    activeIngredient: 'Warfarin',
    dosage: '5mg',
    uses: 'Chống đông máu, phòng ngừa đột quỵ',
    symptoms: ['rung nhĩ', 'huyết khối', 'phòng ngừa đột quỵ'],
    price: 28000,
    manufacturer: 'Dược phẩm Hà Nội',
    sideEffects: ['Chảy máu', 'Bầm tím', 'Đau đầu'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc và theo dõi INR'
  },
  {
    id: '35',
    name: 'Clopidogrel',
    ingredient: 'Clopidogrel 75mg',
    activeIngredient: 'Clopidogrel',
    dosage: '75mg',
    uses: 'Chống đông máu, phòng ngừa đột quỵ',
    symptoms: ['bệnh mạch vành', 'đột quỵ', 'huyết khối'],
    price: 85000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chảy máu', 'Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '36',
    name: 'Acenocoumarol',
    ingredient: 'Acenocoumarol 4mg',
    activeIngredient: 'Acenocoumarol',
    dosage: '4mg',
    uses: 'Chống đông máu, phòng ngừa đột quỵ',
    symptoms: ['rung nhĩ', 'huyết khối', 'phòng ngừa đột quỵ'],
    price: 32000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Chảy máu', 'Bầm tím', 'Đau đầu'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc và theo dõi INR'
  },
  {
    id: '37',
    name: 'Dabigatran',
    ingredient: 'Dabigatran 150mg',
    activeIngredient: 'Dabigatran',
    dosage: '150mg',
    uses: 'Chống đông máu, phòng ngừa đột quỵ',
    symptoms: ['rung nhĩ', 'huyết khối', 'phòng ngừa đột quỵ'],
    price: 150000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chảy máu', 'Đau bụng', 'Buồn nôn'],
    instructions: 'Uống 1 viên 2 lần/ngày, cần đơn thuốc'
  },
  {
    id: '38',
    name: 'Rivaroxaban',
    ingredient: 'Rivaroxaban 20mg',
    activeIngredient: 'Rivaroxaban',
    dosage: '20mg',
    uses: 'Chống đông máu, phòng ngừa đột quỵ',
    symptoms: ['rung nhĩ', 'huyết khối', 'phòng ngừa đột quỵ'],
    price: 180000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chảy máu', 'Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '39',
    name: 'Apixaban',
    ingredient: 'Apixaban 5mg',
    activeIngredient: 'Apixaban',
    dosage: '5mg',
    uses: 'Chống đông máu, phòng ngừa đột quỵ',
    symptoms: ['rung nhĩ', 'huyết khối', 'phòng ngừa đột quỵ'],
    price: 200000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chảy máu', 'Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên 2 lần/ngày, cần đơn thuốc'
  },
  {
    id: '40',
    name: 'Edoxaban',
    ingredient: 'Edoxaban 60mg',
    activeIngredient: 'Edoxaban',
    dosage: '60mg',
    uses: 'Chống đông máu, phòng ngừa đột quỵ',
    symptoms: ['rung nhĩ', 'huyết khối', 'phòng ngừa đột quỵ'],
    price: 220000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chảy máu', 'Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày, cần đơn thuốc'
  },
  {
    id: '41',
    name: 'Alendronate',
    ingredient: 'Alendronate 70mg',
    activeIngredient: 'Alendronate',
    dosage: '70mg',
    uses: 'Điều trị loãng xương',
    symptoms: ['loãng xương', 'gãy xương', 'đau xương'],
    price: 120000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau dạ dày', 'Ợ chua', 'Đau xương'],
    instructions: 'Uống 1 viên mỗi tuần vào buổi sáng khi đói, cần đơn thuốc'
  },
  {
    id: '42',
    name: 'Risedronate',
    ingredient: 'Risedronate 35mg',
    activeIngredient: 'Risedronate',
    dosage: '35mg',
    uses: 'Điều trị loãng xương',
    symptoms: ['loãng xương', 'gãy xương', 'đau xương'],
    price: 150000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau dạ dày', 'Ợ chua', 'Đau xương'],
    instructions: 'Uống 1 viên mỗi tuần vào buổi sáng khi đói, cần đơn thuốc'
  },
  {
    id: '43',
    name: 'Calcium Carbonate',
    ingredient: 'Calcium Carbonate 500mg',
    activeIngredient: 'Calcium',
    dosage: '500mg',
    uses: 'Bổ sung canxi, phòng ngừa loãng xương',
    symptoms: ['thiếu canxi', 'loãng xương', 'đau xương'],
    price: 25000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Táo bón', 'Đầy bụng', 'Buồn nôn'],
    instructions: 'Uống 1-2 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '44',
    name: 'Vitamin D3',
    ingredient: 'Cholecalciferol 1000IU',
    activeIngredient: 'Vitamin D3',
    dosage: '1000IU',
    uses: 'Bổ sung vitamin D, hỗ trợ hấp thu canxi',
    symptoms: ['thiếu vitamin D', 'loãng xương', 'yếu xương'],
    price: 35000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Chán ăn'],
    instructions: 'Uống 1 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '45',
    name: 'Iron Sulfate',
    ingredient: 'Iron Sulfate 325mg',
    activeIngredient: 'Iron',
    dosage: '325mg',
    uses: 'Bổ sung sắt, điều trị thiếu máu',
    symptoms: ['thiếu máu', 'mệt mỏi', 'hoa mắt', 'chóng mặt'],
    price: 28000,
    manufacturer: 'Dược phẩm Hà Nội',
    sideEffects: ['Táo bón', 'Đau bụng', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '46',
    name: 'Folic Acid',
    ingredient: 'Folic Acid 5mg',
    activeIngredient: 'Folic Acid',
    dosage: '5mg',
    uses: 'Bổ sung axit folic, phòng ngừa dị tật thai nhi',
    symptoms: ['thiếu axit folic', 'thiếu máu', 'mang thai'],
    price: 22000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '47',
    name: 'Vitamin B12',
    ingredient: 'Cyanocobalamin 1000mcg',
    activeIngredient: 'Vitamin B12',
    dosage: '1000mcg',
    uses: 'Bổ sung vitamin B12, điều trị thiếu máu',
    symptoms: ['thiếu vitamin B12', 'thiếu máu', 'mệt mỏi'],
    price: 45000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '48',
    name: 'Omega-3',
    ingredient: 'Fish Oil 1000mg',
    activeIngredient: 'Omega-3',
    dosage: '1000mg',
    uses: 'Bổ sung omega-3, hỗ trợ tim mạch',
    symptoms: ['bệnh tim mạch', 'cholesterol cao', 'viêm khớp'],
    price: 85000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Ợ tanh', 'Buồn nôn', 'Đau bụng'],
    instructions: 'Uống 1-2 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '49',
    name: 'Glucosamine',
    ingredient: 'Glucosamine 1500mg',
    activeIngredient: 'Glucosamine',
    dosage: '1500mg',
    uses: 'Hỗ trợ điều trị viêm khớp, đau khớp',
    symptoms: ['viêm khớp', 'đau khớp', 'thoái hóa khớp'],
    price: 120000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '50',
    name: 'Chondroitin',
    ingredient: 'Chondroitin 400mg',
    activeIngredient: 'Chondroitin',
    dosage: '400mg',
    uses: 'Hỗ trợ điều trị viêm khớp, đau khớp',
    symptoms: ['viêm khớp', 'đau khớp', 'thoái hóa khớp'],
    price: 95000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '51',
    name: 'Melatonin',
    ingredient: 'Melatonin 3mg',
    activeIngredient: 'Melatonin',
    dosage: '3mg',
    uses: 'Điều trị mất ngủ, rối loạn giấc ngủ',
    symptoms: ['mất ngủ', 'rối loạn giấc ngủ', 'jet lag'],
    price: 65000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn ngủ', 'Chóng mặt', 'Đau đầu'],
    instructions: 'Uống 1 viên 30 phút trước khi ngủ'
  },
  {
    id: '52',
    name: '5-HTP',
    ingredient: '5-HTP 100mg',
    activeIngredient: '5-HTP',
    dosage: '100mg',
    uses: 'Hỗ trợ điều trị trầm cảm, mất ngủ',
    symptoms: ['trầm cảm', 'mất ngủ', 'lo âu'],
    price: 88000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Chóng mặt'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '53',
    name: 'St. John\'s Wort',
    ingredient: 'St. John\'s Wort 300mg',
    activeIngredient: 'Hypericum',
    dosage: '300mg',
    uses: 'Hỗ trợ điều trị trầm cảm nhẹ',
    symptoms: ['trầm cảm nhẹ', 'lo âu', 'mất ngủ'],
    price: 75000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Chóng mặt'],
    instructions: 'Uống 1 viên 3 lần/ngày'
  },
  {
    id: '54',
    name: 'Ginkgo Biloba',
    ingredient: 'Ginkgo Biloba 120mg',
    activeIngredient: 'Ginkgo Biloba',
    dosage: '120mg',
    uses: 'Cải thiện trí nhớ, tuần hoàn não',
    symptoms: ['suy giảm trí nhớ', 'chóng mặt', 'đau đầu'],
    price: 68000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đau đầu', 'Chóng mặt', 'Buồn nôn'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '55',
    name: 'Ginseng',
    ingredient: 'Ginseng 500mg',
    activeIngredient: 'Ginseng',
    dosage: '500mg',
    uses: 'Tăng cường sức khỏe, chống mệt mỏi',
    symptoms: ['mệt mỏi', 'suy nhược', 'stress'],
    price: 95000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Mất ngủ', 'Đau đầu', 'Tăng huyết áp'],
    instructions: 'Uống 1 viên mỗi ngày vào buổi sáng'
  },
  {
    id: '56',
    name: 'Probiotics',
    ingredient: 'Lactobacillus 10 billion CFU',
    activeIngredient: 'Probiotics',
    dosage: '10 billion CFU',
    uses: 'Cải thiện hệ tiêu hóa, tăng cường miễn dịch',
    symptoms: ['rối loạn tiêu hóa', 'tiêu chảy', 'táo bón'],
    price: 120000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đầy bụng', 'Buồn nôn', 'Tiêu chảy nhẹ'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '57',
    name: 'Digestive Enzymes',
    ingredient: 'Digestive Enzymes 500mg',
    activeIngredient: 'Digestive Enzymes',
    dosage: '500mg',
    uses: 'Hỗ trợ tiêu hóa, giảm đầy bụng',
    symptoms: ['đầy bụng', 'khó tiêu', 'rối loạn tiêu hóa'],
    price: 85000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên trước bữa ăn'
  },
  {
    id: '58',
    name: 'L-Glutamine',
    ingredient: 'L-Glutamine 500mg',
    activeIngredient: 'L-Glutamine',
    dosage: '500mg',
    uses: 'Hỗ trợ tiêu hóa, tăng cường miễn dịch',
    symptoms: ['rối loạn tiêu hóa', 'viêm ruột', 'suy nhược'],
    price: 78000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '59',
    name: 'Coenzyme Q10',
    ingredient: 'Coenzyme Q10 100mg',
    activeIngredient: 'Coenzyme Q10',
    dosage: '100mg',
    uses: 'Chống oxy hóa, hỗ trợ tim mạch',
    symptoms: ['bệnh tim mạch', 'mệt mỏi', 'suy nhược'],
    price: 150000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Chóng mặt'],
    instructions: 'Uống 1 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '60',
    name: 'Alpha Lipoic Acid',
    ingredient: 'Alpha Lipoic Acid 300mg',
    activeIngredient: 'Alpha Lipoic Acid',
    dosage: '300mg',
    uses: 'Chống oxy hóa, hỗ trợ điều trị tiểu đường',
    symptoms: ['tiểu đường', 'tổn thương thần kinh', 'mệt mỏi'],
    price: 180000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Chóng mặt'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '61',
    name: 'N-Acetyl Cysteine',
    ingredient: 'N-Acetyl Cysteine 600mg',
    activeIngredient: 'N-Acetyl Cysteine',
    dosage: '600mg',
    uses: 'Chống oxy hóa, hỗ trợ gan',
    symptoms: ['bệnh gan', 'nhiễm độc', 'mệt mỏi'],
    price: 95000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '62',
    name: 'Milk Thistle',
    ingredient: 'Milk Thistle 250mg',
    activeIngredient: 'Silymarin',
    dosage: '250mg',
    uses: 'Hỗ trợ gan, giải độc',
    symptoms: ['bệnh gan', 'nhiễm độc', 'mệt mỏi'],
    price: 88000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 3 lần/ngày'
  },
  {
    id: '63',
    name: 'Turmeric',
    ingredient: 'Turmeric 500mg',
    activeIngredient: 'Curcumin',
    dosage: '500mg',
    uses: 'Chống viêm, chống oxy hóa',
    symptoms: ['viêm khớp', 'đau khớp', 'viêm dạ dày'],
    price: 65000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '64',
    name: 'Ginger',
    ingredient: 'Ginger 500mg',
    activeIngredient: 'Ginger',
    dosage: '500mg',
    uses: 'Chống buồn nôn, hỗ trợ tiêu hóa',
    symptoms: ['buồn nôn', 'say tàu xe', 'đầy bụng'],
    price: 45000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Ợ chua', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên khi cần thiết'
  },
  {
    id: '65',
    name: 'Peppermint Oil',
    ingredient: 'Peppermint Oil 0.2ml',
    activeIngredient: 'Peppermint Oil',
    dosage: '0.2ml',
    uses: 'Hỗ trợ tiêu hóa, giảm đầy bụng',
    symptoms: ['đầy bụng', 'khó tiêu', 'đau bụng'],
    price: 55000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Ợ chua', 'Đau bụng', 'Buồn nôn'],
    instructions: 'Uống 1 viên trước bữa ăn'
  },
  {
    id: '66',
    name: 'Aloe Vera',
    ingredient: 'Aloe Vera 200mg',
    activeIngredient: 'Aloe Vera',
    dosage: '200mg',
    uses: 'Hỗ trợ tiêu hóa, làm mát gan',
    symptoms: ['táo bón', 'nóng gan', 'mụn nhọt'],
    price: 42000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Tiêu chảy', 'Đau bụng', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '67',
    name: 'Psyllium Husk',
    ingredient: 'Psyllium Husk 500mg',
    activeIngredient: 'Psyllium',
    dosage: '500mg',
    uses: 'Hỗ trợ tiêu hóa, điều trị táo bón',
    symptoms: ['táo bón', 'rối loạn tiêu hóa', 'đầy bụng'],
    price: 38000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Đầy bụng', 'Tiêu chảy', 'Buồn nôn'],
    instructions: 'Uống 1 viên 2 lần/ngày với nhiều nước'
  },
  {
    id: '68',
    name: 'Activated Charcoal',
    ingredient: 'Activated Charcoal 250mg',
    activeIngredient: 'Activated Charcoal',
    dosage: '250mg',
    uses: 'Hấp thu độc tố, điều trị ngộ độc',
    symptoms: ['ngộ độc', 'tiêu chảy', 'đầy bụng'],
    price: 35000,
    manufacturer: 'Dược phẩm Hà Nội',
    sideEffects: ['Táo bón', 'Phân đen', 'Buồn nôn'],
    instructions: 'Uống 1-2 viên khi cần thiết'
  },
  {
    id: '69',
    name: 'Bentonite Clay',
    ingredient: 'Bentonite Clay 500mg',
    activeIngredient: 'Bentonite Clay',
    dosage: '500mg',
    uses: 'Hấp thu độc tố, làm sạch ruột',
    symptoms: ['ngộ độc', 'tiêu chảy', 'đầy bụng'],
    price: 48000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Táo bón', 'Buồn nôn', 'Đau bụng'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '70',
    name: 'Chlorella',
    ingredient: 'Chlorella 500mg',
    activeIngredient: 'Chlorella',
    dosage: '500mg',
    uses: 'Giải độc, tăng cường miễn dịch',
    symptoms: ['nhiễm độc', 'mệt mỏi', 'suy nhược'],
    price: 85000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '71',
    name: 'Spirulina',
    ingredient: 'Spirulina 500mg',
    activeIngredient: 'Spirulina',
    dosage: '500mg',
    uses: 'Bổ sung dinh dưỡng, tăng cường miễn dịch',
    symptoms: ['suy nhược', 'thiếu dinh dưỡng', 'mệt mỏi'],
    price: 75000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '72',
    name: 'Wheat Grass',
    ingredient: 'Wheat Grass 500mg',
    activeIngredient: 'Wheat Grass',
    dosage: '500mg',
    uses: 'Giải độc, tăng cường miễn dịch',
    symptoms: ['nhiễm độc', 'mệt mỏi', 'suy nhược'],
    price: 68000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '73',
    name: 'Barley Grass',
    ingredient: 'Barley Grass 500mg',
    activeIngredient: 'Barley Grass',
    dosage: '500mg',
    uses: 'Giải độc, tăng cường miễn dịch',
    symptoms: ['nhiễm độc', 'mệt mỏi', 'suy nhược'],
    price: 62000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '74',
    name: 'Moringa',
    ingredient: 'Moringa 500mg',
    activeIngredient: 'Moringa',
    dosage: '500mg',
    uses: 'Bổ sung dinh dưỡng, tăng cường miễn dịch',
    symptoms: ['suy nhược', 'thiếu dinh dưỡng', 'mệt mỏi'],
    price: 58000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '75',
    name: 'Ashwagandha',
    ingredient: 'Ashwagandha 500mg',
    activeIngredient: 'Ashwagandha',
    dosage: '500mg',
    uses: 'Giảm stress, tăng cường sức khỏe',
    symptoms: ['stress', 'lo âu', 'mệt mỏi'],
    price: 95000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Chóng mặt'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '76',
    name: 'Rhodiola Rosea',
    ingredient: 'Rhodiola Rosea 200mg',
    activeIngredient: 'Rhodiola Rosea',
    dosage: '200mg',
    uses: 'Tăng cường sức khỏe, chống mệt mỏi',
    symptoms: ['mệt mỏi', 'stress', 'suy nhược'],
    price: 120000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Mất ngủ', 'Đau đầu', 'Chóng mặt'],
    instructions: 'Uống 1 viên mỗi ngày vào buổi sáng'
  },
  {
    id: '77',
    name: 'Maca Root',
    ingredient: 'Maca Root 500mg',
    activeIngredient: 'Maca Root',
    dosage: '500mg',
    uses: 'Tăng cường sinh lý, sức khỏe',
    symptoms: ['suy nhược', 'mệt mỏi', 'giảm ham muốn'],
    price: 88000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Mất ngủ', 'Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '78',
    name: 'Tribulus Terrestris',
    ingredient: 'Tribulus Terrestris 500mg',
    activeIngredient: 'Tribulus Terrestris',
    dosage: '500mg',
    uses: 'Tăng cường sinh lý, sức khỏe',
    symptoms: ['suy nhược', 'mệt mỏi', 'giảm ham muốn'],
    price: 75000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Mất ngủ', 'Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '79',
    name: 'Saw Palmetto',
    ingredient: 'Saw Palmetto 320mg',
    activeIngredient: 'Saw Palmetto',
    dosage: '320mg',
    uses: 'Hỗ trợ điều trị phì đại tuyến tiền liệt',
    symptoms: ['phì đại tuyến tiền liệt', 'tiểu đêm', 'tiểu khó'],
    price: 95000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Chóng mặt'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '80',
    name: 'Pumpkin Seed Oil',
    ingredient: 'Pumpkin Seed Oil 1000mg',
    activeIngredient: 'Pumpkin Seed Oil',
    dosage: '1000mg',
    uses: 'Hỗ trợ điều trị phì đại tuyến tiền liệt',
    symptoms: ['phì đại tuyến tiền liệt', 'tiểu đêm', 'tiểu khó'],
    price: 68000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '81',
    name: 'Cranberry',
    ingredient: 'Cranberry 500mg',
    activeIngredient: 'Cranberry',
    dosage: '500mg',
    uses: 'Hỗ trợ điều trị viêm đường tiết niệu',
    symptoms: ['viêm đường tiết niệu', 'tiểu buốt', 'tiểu rắt'],
    price: 55000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '82',
    name: 'D-Mannose',
    ingredient: 'D-Mannose 500mg',
    activeIngredient: 'D-Mannose',
    dosage: '500mg',
    uses: 'Hỗ trợ điều trị viêm đường tiết niệu',
    symptoms: ['viêm đường tiết niệu', 'tiểu buốt', 'tiểu rắt'],
    price: 85000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '83',
    name: 'Bromelain',
    ingredient: 'Bromelain 500mg',
    activeIngredient: 'Bromelain',
    dosage: '500mg',
    uses: 'Chống viêm, hỗ trợ tiêu hóa',
    symptoms: ['viêm khớp', 'đau khớp', 'đầy bụng'],
    price: 72000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '84',
    name: 'Papain',
    ingredient: 'Papain 500mg',
    activeIngredient: 'Papain',
    dosage: '500mg',
    uses: 'Hỗ trợ tiêu hóa, chống viêm',
    symptoms: ['đầy bụng', 'khó tiêu', 'viêm khớp'],
    price: 65000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên trước bữa ăn'
  },
  {
    id: '85',
    name: 'Serrapeptase',
    ingredient: 'Serrapeptase 10mg',
    activeIngredient: 'Serrapeptase',
    dosage: '10mg',
    uses: 'Chống viêm, giảm đau',
    symptoms: ['viêm khớp', 'đau khớp', 'viêm xoang'],
    price: 120000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên 2 lần/ngày khi đói'
  },
  {
    id: '86',
    name: 'Nattokinase',
    ingredient: 'Nattokinase 2000FU',
    activeIngredient: 'Nattokinase',
    dosage: '2000FU',
    uses: 'Chống đông máu, cải thiện tuần hoàn',
    symptoms: ['huyết khối', 'tuần hoàn kém', 'tăng huyết áp'],
    price: 150000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Chảy máu', 'Đau đầu', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '87',
    name: 'L-Carnitine',
    ingredient: 'L-Carnitine 500mg',
    activeIngredient: 'L-Carnitine',
    dosage: '500mg',
    uses: 'Tăng cường năng lượng, hỗ trợ tim mạch',
    symptoms: ['mệt mỏi', 'suy nhược', 'bệnh tim mạch'],
    price: 95000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Chóng mặt'],
    instructions: 'Uống 1 viên 2 lần/ngày'
  },
  {
    id: '88',
    name: 'Creatine',
    ingredient: 'Creatine 5g',
    activeIngredient: 'Creatine',
    dosage: '5g',
    uses: 'Tăng cường sức mạnh, phát triển cơ bắp',
    symptoms: ['mệt mỏi', 'suy nhược', 'yếu cơ'],
    price: 85000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đầy bụng', 'Tiêu chảy', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày với nhiều nước'
  },
  {
    id: '89',
    name: 'BCAA',
    ingredient: 'BCAA 2000mg',
    activeIngredient: 'BCAA',
    dosage: '2000mg',
    uses: 'Tăng cường cơ bắp, giảm mệt mỏi',
    symptoms: ['mệt mỏi', 'suy nhược', 'yếu cơ'],
    price: 120000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên trước và sau tập luyện'
  },
  {
    id: '90',
    name: 'Whey Protein',
    ingredient: 'Whey Protein 25g',
    activeIngredient: 'Whey Protein',
    dosage: '25g',
    uses: 'Bổ sung protein, phát triển cơ bắp',
    symptoms: ['thiếu protein', 'suy nhược', 'yếu cơ'],
    price: 180000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đầy bụng', 'Tiêu chảy', 'Buồn nôn'],
    instructions: 'Uống 1 viên sau tập luyện hoặc bữa ăn'
  },
  {
    id: '91',
    name: 'Casein Protein',
    ingredient: 'Casein Protein 25g',
    activeIngredient: 'Casein Protein',
    dosage: '25g',
    uses: 'Bổ sung protein, phát triển cơ bắp',
    symptoms: ['thiếu protein', 'suy nhược', 'yếu cơ'],
    price: 160000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Đầy bụng', 'Tiêu chảy', 'Buồn nôn'],
    instructions: 'Uống 1 viên trước khi ngủ'
  },
  {
    id: '92',
    name: 'Collagen',
    ingredient: 'Collagen 1000mg',
    activeIngredient: 'Collagen',
    dosage: '1000mg',
    uses: 'Làm đẹp da, tóc, móng',
    symptoms: ['lão hóa da', 'rụng tóc', 'móng yếu'],
    price: 150000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '93',
    name: 'Hyaluronic Acid',
    ingredient: 'Hyaluronic Acid 100mg',
    activeIngredient: 'Hyaluronic Acid',
    dosage: '100mg',
    uses: 'Làm đẹp da, chống lão hóa',
    symptoms: ['lão hóa da', 'khô da', 'nếp nhăn'],
    price: 180000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '94',
    name: 'Biotin',
    ingredient: 'Biotin 5000mcg',
    activeIngredient: 'Biotin',
    dosage: '5000mcg',
    uses: 'Làm đẹp tóc, móng, da',
    symptoms: ['rụng tóc', 'móng yếu', 'da khô'],
    price: 65000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '95',
    name: 'Zinc',
    ingredient: 'Zinc 15mg',
    activeIngredient: 'Zinc',
    dosage: '15mg',
    uses: 'Tăng cường miễn dịch, làm đẹp da',
    symptoms: ['suy giảm miễn dịch', 'mụn nhọt', 'rụng tóc'],
    price: 45000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày sau bữa ăn'
  },
  {
    id: '96',
    name: 'Selenium',
    ingredient: 'Selenium 100mcg',
    activeIngredient: 'Selenium',
    dosage: '100mcg',
    uses: 'Chống oxy hóa, tăng cường miễn dịch',
    symptoms: ['suy giảm miễn dịch', 'mệt mỏi', 'lão hóa'],
    price: 55000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '97',
    name: 'Magnesium',
    ingredient: 'Magnesium 400mg',
    activeIngredient: 'Magnesium',
    dosage: '400mg',
    uses: 'Hỗ trợ thần kinh, cơ bắp',
    symptoms: ['chuột rút', 'mệt mỏi', 'mất ngủ'],
    price: 48000,
    manufacturer: 'Dược phẩm Việt Nam',
    sideEffects: ['Tiêu chảy', 'Đau bụng', 'Buồn nôn'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '98',
    name: 'Potassium',
    ingredient: 'Potassium 99mg',
    activeIngredient: 'Potassium',
    dosage: '99mg',
    uses: 'Hỗ trợ tim mạch, cơ bắp',
    symptoms: ['chuột rút', 'mệt mỏi', 'tăng huyết áp'],
    price: 38000,
    manufacturer: 'Dược phẩm TP.HCM',
    sideEffects: ['Buồn nôn', 'Đau bụng', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '99',
    name: 'Chromium',
    ingredient: 'Chromium 200mcg',
    activeIngredient: 'Chromium',
    dosage: '200mcg',
    uses: 'Hỗ trợ điều trị tiểu đường',
    symptoms: ['tiểu đường', 'tăng đường huyết', 'mệt mỏi'],
    price: 42000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  },
  {
    id: '100',
    name: 'Vanadium',
    ingredient: 'Vanadium 50mcg',
    activeIngredient: 'Vanadium',
    dosage: '50mcg',
    uses: 'Hỗ trợ điều trị tiểu đường',
    symptoms: ['tiểu đường', 'tăng đường huyết', 'mệt mỏi'],
    price: 58000,
    manufacturer: 'Dược phẩm Quốc tế',
    sideEffects: ['Buồn nôn', 'Đau đầu', 'Tiêu chảy'],
    instructions: 'Uống 1 viên mỗi ngày'
  }
]

export interface Product {
  id: string
  name: string
  ingredient: string
  activeIngredient: string
  dosage: string
  uses: string
  symptoms: string[]
  price: number
  manufacturer: string
  sideEffects: string[]
  instructions: string
} 