import { Product } from '@/types/product'

// Mảng hình ảnh thực tế cho 30 sản phẩm khác nhau
const productImages = [
  // Thuốc giảm đau
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Vitamin
  'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Thuốc tiêu hóa
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Thuốc dị ứng
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Kháng sinh
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Thuốc tiểu đường
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Thuốc tim mạch
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Thuốc xương khớp
  'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Thuốc hô hấp
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Thực phẩm chức năng
  'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center&q=80',
  
  // Hình ảnh thực tế từ Unsplash
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center&q=80',
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center&q=80',
]

// Dữ liệu sản phẩm mở rộng với nhiều hình ảnh đa dạng
export const allProducts: Product[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    description: 'Thuốc giảm đau, hạ sốt hiệu quả',
    price: 15000,
    image: '/images/products/paracetamol.jpg',
    category: 'Thuốc giảm đau',
    stock: 100,
    prescription: false,
    manufacturer: 'Dược phẩm Quốc tế',
    origin: 'Việt Nam',
    expiry: '36 tháng',
    dosage: '1-2 viên/lần, tối đa 4 lần/ngày',
    ingredients: 'Paracetamol 500mg',
    sideEffects: 'Buồn nôn, đau dạ dày (hiếm gặp)',
    contraindications: 'Người mẫn cảm với Paracetamol',
    storage: 'Bảo quản nơi khô ráo, tránh ánh sáng trực tiếp',
    packaging: 'Hộp 10 vỉ x 10 viên',
    usage: 'Uống sau bữa ăn',
    target: 'Người lớn và trẻ em trên 12 tuổi',
    benefits: [
      'Giảm đau đầu, đau răng, đau cơ',
      'Hạ sốt nhanh chóng',
      'An toàn cho dạ dày',
      'Không gây buồn ngủ'
    ],
    reviews: [
      { user: 'Nguyễn Văn A', rating: 5, comment: 'Thuốc rất hiệu quả, giảm đau nhanh' },
      { user: 'Trần Thị B', rating: 4, comment: 'Giá cả hợp lý, chất lượng tốt' },
      { user: 'Lê Văn C', rating: 5, comment: 'Đã sử dụng nhiều lần, rất hài lòng' }
    ]
  },
  {
    id: '2',
    name: 'Vitamin C 1000mg',
    description: 'Tăng cường sức đề kháng, chống oxy hóa',
    price: 35000,
    image: productImages[1],
    category: 'Vitamin',
    stock: 50,
    prescription: false,
    manufacturer: 'Công ty TNHH Dược phẩm ABC',
    origin: 'Việt Nam',
    expiry: '24 tháng',
    dosage: '1 viên/ngày',
    ingredients: 'Vitamin C 1000mg, tá dược vừa đủ',
    sideEffects: 'Tiêu chảy nhẹ (nếu dùng quá liều)',
    contraindications: 'Người bị sỏi thận',
    storage: 'Bảo quản nơi khô ráo, nhiệt độ dưới 30°C',
    packaging: 'Lọ 60 viên',
    usage: 'Uống sau bữa ăn sáng',
    target: 'Người lớn cần bổ sung vitamin C',
    benefits: [
      'Tăng cường hệ miễn dịch',
      'Chống oxy hóa, làm đẹp da',
      'Hỗ trợ hấp thu sắt',
      'Tăng sức đề kháng'
    ],
    reviews: [
      { user: 'Phạm Thị D', rating: 5, comment: 'Uống thường xuyên, ít bị cảm cúm' },
      { user: 'Hoàng Văn E', rating: 4, comment: 'Viên thuốc dễ uống, hiệu quả tốt' },
      { user: 'Vũ Thị F', rating: 5, comment: 'Da đẹp hơn sau khi uống vitamin C' }
    ]
  },
  {
    id: '3',
    name: 'Omeprazole 20mg',
    description: 'Điều trị viêm loét dạ dày, trào ngược axit',
    price: 45000,
    image: productImages[2],
    category: 'Thuốc tiêu hóa',
    stock: 30,
    prescription: true,
    manufacturer: 'Công ty Dược phẩm XYZ',
    origin: 'Việt Nam',
    expiry: '36 tháng',
    dosage: '1 viên/ngày, uống trước bữa sáng',
    ingredients: 'Omeprazole 20mg',
    sideEffects: 'Đau đầu, buồn nôn, tiêu chảy',
    contraindications: 'Phụ nữ có thai, trẻ em dưới 18 tuổi',
    storage: 'Bảo quản nơi khô ráo, tránh ánh sáng',
    packaging: 'Hộp 3 vỉ x 10 viên',
    usage: 'Uống trước bữa sáng 30 phút',
    target: 'Người bị viêm loét dạ dày, trào ngược axit',
    benefits: [
      'Giảm tiết axit dạ dày',
      'Điều trị viêm loét dạ dày',
      'Chống trào ngược axit',
      'Bảo vệ niêm mạc dạ dày'
    ],
    reviews: [
      { user: 'Đỗ Văn G', rating: 4, comment: 'Giảm đau dạ dày rõ rệt' },
      { user: 'Ngô Thị H', rating: 5, comment: 'Bác sĩ kê đơn, hiệu quả tốt' },
      { user: 'Lý Văn I', rating: 4, comment: 'Uống đúng liều, không có tác dụng phụ' }
    ]
  },
  {
    id: '4',
    name: 'Cetirizine 10mg',
    description: 'Thuốc kháng histamine, điều trị dị ứng',
    price: 28000,
    image: productImages[3],
    category: 'Thuốc dị ứng',
    stock: 75,
    prescription: false,
  },
  {
    id: '5',
    name: 'Ibuprofen 400mg',
    description: 'Thuốc chống viêm, giảm đau',
    price: 25000,
    image: productImages[4],
    category: 'Thuốc giảm đau',
    stock: 60,
    prescription: false,
  },
  {
    id: '6',
    name: 'Vitamin D3 1000IU',
    description: 'Bổ sung vitamin D, tăng cường xương',
    price: 35000,
    image: productImages[5],
    category: 'Vitamin',
    stock: 40,
    prescription: false,
  },
  {
    id: '7',
    name: 'Lansoprazole 30mg',
    description: 'Điều trị loét dạ dày, tá tràng',
    price: 68000,
    image: productImages[6],
    category: 'Thuốc tiêu hóa',
    stock: 25,
    prescription: true,
  },
  {
    id: '8',
    name: 'Loratadine 10mg',
    description: 'Thuốc kháng histamine, không gây buồn ngủ',
    price: 32000,
    image: productImages[7],
    category: 'Thuốc dị ứng',
    stock: 80,
    prescription: false,
  },
  {
    id: '9',
    name: 'Amoxicillin 500mg',
    description: 'Kháng sinh điều trị nhiễm khuẩn',
    price: 55000,
    image: productImages[8],
    category: 'Kháng sinh',
    stock: 45,
    prescription: true,
  },
  {
    id: '10',
    name: 'Metformin 500mg',
    description: 'Điều trị tiểu đường type 2',
    price: 85000,
    image: productImages[9],
    category: 'Thuốc tiểu đường',
    stock: 35,
    prescription: true,
  },
  {
    id: '11',
    name: 'Losartan 50mg',
    description: 'Điều trị tăng huyết áp',
    price: 95000,
    image: productImages[10],
    category: 'Thuốc tim mạch',
    stock: 30,
    prescription: true,
  },
  {
    id: '12',
    name: 'Atorvastatin 20mg',
    description: 'Giảm cholesterol, phòng ngừa bệnh tim mạch',
    price: 120000,
    image: productImages[11],
    category: 'Thuốc tim mạch',
    stock: 25,
    prescription: true,
  },
  {
    id: '13',
    name: 'Aspirin 100mg',
    description: 'Giảm đau, hạ sốt, chống đông máu',
    price: 18000,
    image: productImages[12],
    category: 'Thuốc giảm đau',
    stock: 90,
    prescription: false,
  },
  {
    id: '14',
    name: 'Ranitidine 150mg',
    description: 'Điều trị viêm loét dạ dày, trào ngược axit',
    price: 38000,
    image: productImages[13],
    category: 'Thuốc tiêu hóa',
    stock: 55,
    prescription: false,
  },
  {
    id: '15',
    name: 'Ciprofloxacin 500mg',
    description: 'Kháng sinh điều trị nhiễm khuẩn',
    price: 65000,
    image: productImages[14],
    category: 'Kháng sinh',
    stock: 40,
    prescription: true,
  },
  {
    id: '16',
    name: 'Azithromycin 500mg',
    description: 'Kháng sinh điều trị nhiễm khuẩn đường hô hấp',
    price: 72000,
    image: productImages[15],
    category: 'Kháng sinh',
    stock: 35,
    prescription: true,
  },
  {
    id: '17',
    name: 'Fexofenadine 180mg',
    description: 'Điều trị dị ứng, không gây buồn ngủ',
    price: 45000,
    image: productImages[16],
    category: 'Thuốc dị ứng',
    stock: 65,
    prescription: false,
  },
  {
    id: '18',
    name: 'Montelukast 10mg',
    description: 'Điều trị hen suyễn, viêm mũi dị ứng',
    price: 88000,
    image: productImages[17],
    category: 'Thuốc hô hấp',
    stock: 30,
    prescription: true,
  },
  {
    id: '19',
    name: 'Pantoprazole 40mg',
    description: 'Điều trị viêm loét dạ dày, trào ngược axit',
    price: 68000,
    image: productImages[18],
    category: 'Thuốc tiêu hóa',
    stock: 40,
    prescription: true,
  },
  {
    id: '20',
    name: 'Amlodipine 5mg',
    description: 'Điều trị tăng huyết áp, đau thắt ngực',
    price: 78000,
    image: productImages[19],
    category: 'Thuốc tim mạch',
    stock: 35,
    prescription: true,
  },
  {
    id: '21',
    name: 'Alendronate 70mg',
    description: 'Điều trị loãng xương',
    price: 120000,
    image: productImages[20],
    category: 'Thuốc xương khớp',
    stock: 20,
    prescription: true,
  },
  {
    id: '22',
    name: 'Risedronate 35mg',
    description: 'Điều trị loãng xương',
    price: 150000,
    image: productImages[21],
    category: 'Thuốc xương khớp',
    stock: 15,
    prescription: true,
  },
  {
    id: '23',
    name: 'Calcium Carbonate 500mg',
    description: 'Bổ sung canxi, phòng ngừa loãng xương',
    price: 25000,
    image: productImages[22],
    category: 'Vitamin',
    stock: 70,
    prescription: false,
  },
  {
    id: '24',
    name: 'Iron Sulfate 325mg',
    description: 'Bổ sung sắt, điều trị thiếu máu',
    price: 28000,
    image: productImages[23],
    category: 'Vitamin',
    stock: 60,
    prescription: false,
  },
  {
    id: '25',
    name: 'Folic Acid 5mg',
    description: 'Bổ sung axit folic, phòng ngừa dị tật thai nhi',
    price: 22000,
    image: productImages[24],
    category: 'Vitamin',
    stock: 80,
    prescription: false,
  },
  {
    id: '26',
    name: 'Vitamin B12 1000mcg',
    description: 'Bổ sung vitamin B12, điều trị thiếu máu',
    price: 45000,
    image: productImages[25],
    category: 'Vitamin',
    stock: 45,
    prescription: false,
  },
  {
    id: '27',
    name: 'Omega-3 1000mg',
    description: 'Bổ sung omega-3, hỗ trợ tim mạch',
    price: 85000,
    image: productImages[26],
    category: 'Thực phẩm chức năng',
    stock: 50,
    prescription: false,
  },
  {
    id: '28',
    name: 'Glucosamine 1500mg',
    description: 'Hỗ trợ điều trị viêm khớp, đau khớp',
    price: 120000,
    image: productImages[27],
    category: 'Thuốc xương khớp',
    stock: 30,
    prescription: false,
  },
  {
    id: '29',
    name: 'Melatonin 3mg',
    description: 'Hỗ trợ giấc ngủ, điều trị mất ngủ',
    price: 95000,
    image: productImages[28],
    category: 'Thực phẩm chức năng',
    stock: 40,
    prescription: false,
  },
  {
    id: '30',
    name: 'Probiotics 10 tỷ CFU',
    description: 'Bổ sung lợi khuẩn, hỗ trợ tiêu hóa',
    price: 75000,
    image: productImages[29],
    category: 'Thực phẩm chức năng',
    stock: 55,
    prescription: false,
  },
  // Thêm 70 sản phẩm mới
  {
    id: '31',
    name: 'Diclofenac 50mg',
    description: 'Thuốc chống viêm, giảm đau khớp',
    price: 32000,
    image: productImages[0],
    category: 'Thuốc giảm đau',
    stock: 45,
    prescription: false,
  },
  {
    id: '32',
    name: 'Tramadol 50mg',
    description: 'Thuốc giảm đau mạnh, chỉ định đặc biệt',
    price: 85000,
    image: productImages[1],
    category: 'Thuốc giảm đau',
    stock: 20,
    prescription: true,
  },
  {
    id: '33',
    name: 'Codeine 30mg',
    description: 'Thuốc giảm đau, ho, chỉ định đặc biệt',
    price: 95000,
    image: productImages[2],
    category: 'Thuốc giảm đau',
    stock: 15,
    prescription: true,
  },
  {
    id: '34',
    name: 'Vitamin A 5000IU',
    description: 'Bổ sung vitamin A, tốt cho mắt và da',
    price: 35000,
    image: productImages[3],
    category: 'Vitamin',
    stock: 65,
    prescription: false,
  },
  {
    id: '35',
    name: 'Vitamin E 400IU',
    description: 'Chống oxy hóa, làm đẹp da',
    price: 42000,
    image: productImages[4],
    category: 'Vitamin',
    stock: 55,
    prescription: false,
  },
  {
    id: '36',
    name: 'Vitamin K2 100mcg',
    description: 'Hỗ trợ xương và tim mạch',
    price: 68000,
    image: productImages[5],
    category: 'Vitamin',
    stock: 35,
    prescription: false,
  },
  {
    id: '37',
    name: 'Vitamin B1 100mg',
    description: 'Bổ sung vitamin B1, tốt cho thần kinh',
    price: 28000,
    image: productImages[6],
    category: 'Vitamin',
    stock: 70,
    prescription: false,
  },
  {
    id: '38',
    name: 'Vitamin B6 50mg',
    description: 'Hỗ trợ chuyển hóa protein',
    price: 32000,
    image: productImages[7],
    category: 'Vitamin',
    stock: 60,
    prescription: false,
  },
  {
    id: '39',
    name: 'Esomeprazole 40mg',
    description: 'Điều trị trào ngược axit, loét dạ dày',
    price: 78000,
    image: productImages[8],
    category: 'Thuốc tiêu hóa',
    stock: 30,
    prescription: true,
  },
  {
    id: '40',
    name: 'Domperidone 10mg',
    description: 'Điều trị buồn nôn, nôn',
    price: 45000,
    image: productImages[9],
    category: 'Thuốc tiêu hóa',
    stock: 40,
    prescription: false,
  },
  {
    id: '41',
    name: 'Metoclopramide 10mg',
    description: 'Điều trị buồn nôn, nôn, khó tiêu',
    price: 38000,
    image: productImages[10],
    category: 'Thuốc tiêu hóa',
    stock: 50,
    prescription: false,
  },
  {
    id: '42',
    name: 'Loperamide 2mg',
    description: 'Điều trị tiêu chảy',
    price: 25000,
    image: productImages[11],
    category: 'Thuốc tiêu hóa',
    stock: 80,
    prescription: false,
  },
  {
    id: '43',
    name: 'Diphenhydramine 25mg',
    description: 'Thuốc kháng histamine, gây buồn ngủ',
    price: 22000,
    image: productImages[12],
    category: 'Thuốc dị ứng',
    stock: 75,
    prescription: false,
  },
  {
    id: '44',
    name: 'Chlorpheniramine 4mg',
    description: 'Thuốc kháng histamine, điều trị dị ứng',
    price: 18000,
    image: productImages[13],
    category: 'Thuốc dị ứng',
    stock: 90,
    prescription: false,
  },
  {
    id: '45',
    name: 'Brompheniramine 4mg',
    description: 'Thuốc kháng histamine, điều trị dị ứng',
    price: 20000,
    image: productImages[14],
    category: 'Thuốc dị ứng',
    stock: 65,
    prescription: false,
  },
  {
    id: '46',
    name: 'Doxycycline 100mg',
    description: 'Kháng sinh điều trị nhiễm khuẩn',
    price: 58000,
    image: productImages[15],
    category: 'Kháng sinh',
    stock: 35,
    prescription: true,
  },
  {
    id: '47',
    name: 'Clarithromycin 500mg',
    description: 'Kháng sinh điều trị nhiễm khuẩn đường hô hấp',
    price: 72000,
    image: productImages[16],
    category: 'Kháng sinh',
    stock: 30,
    prescription: true,
  },
  {
    id: '48',
    name: 'Erythromycin 500mg',
    description: 'Kháng sinh điều trị nhiễm khuẩn',
    price: 65000,
    image: productImages[17],
    category: 'Kháng sinh',
    stock: 25,
    prescription: true,
  },
  {
    id: '49',
    name: 'Glibenclamide 5mg',
    description: 'Điều trị tiểu đường type 2',
    price: 45000,
    image: productImages[18],
    category: 'Thuốc tiểu đường',
    stock: 40,
    prescription: true,
  },
  {
    id: '50',
    name: 'Gliclazide 80mg',
    description: 'Điều trị tiểu đường type 2',
    price: 52000,
    image: productImages[19],
    category: 'Thuốc tiểu đường',
    stock: 35,
    prescription: true,
  },
  {
    id: '51',
    name: 'Enalapril 10mg',
    description: 'Điều trị tăng huyết áp, suy tim',
    price: 68000,
    image: productImages[20],
    category: 'Thuốc tim mạch',
    stock: 30,
    prescription: true,
  },
  {
    id: '52',
    name: 'Captopril 25mg',
    description: 'Điều trị tăng huyết áp, suy tim',
    price: 55000,
    image: productImages[21],
    category: 'Thuốc tim mạch',
    stock: 45,
    prescription: true,
  },
  {
    id: '53',
    name: 'Propranolol 40mg',
    description: 'Điều trị tăng huyết áp, đau thắt ngực',
    price: 42000,
    image: productImages[22],
    category: 'Thuốc tim mạch',
    stock: 50,
    prescription: true,
  },
  {
    id: '54',
    name: 'Atenolol 50mg',
    description: 'Điều trị tăng huyết áp, đau thắt ngực',
    price: 48000,
    image: productImages[23],
    category: 'Thuốc tim mạch',
    stock: 40,
    prescription: true,
  },
  {
    id: '55',
    name: 'Simvastatin 20mg',
    description: 'Giảm cholesterol, phòng ngừa bệnh tim mạch',
    price: 85000,
    image: productImages[24],
    category: 'Thuốc tim mạch',
    stock: 35,
    prescription: true,
  },
  {
    id: '56',
    name: 'Pravastatin 40mg',
    description: 'Giảm cholesterol, phòng ngừa bệnh tim mạch',
    price: 92000,
    image: productImages[25],
    category: 'Thuốc tim mạch',
    stock: 25,
    prescription: true,
  },
  {
    id: '57',
    name: 'Ibandronate 150mg',
    description: 'Điều trị loãng xương',
    price: 180000,
    image: productImages[26],
    category: 'Thuốc xương khớp',
    stock: 15,
    prescription: true,
  },
  {
    id: '58',
    name: 'Zoledronic Acid 5mg',
    description: 'Điều trị loãng xương nặng',
    price: 250000,
    image: productImages[27],
    category: 'Thuốc xương khớp',
    stock: 10,
    prescription: true,
  },
  {
    id: '59',
    name: 'Chondroitin 400mg',
    description: 'Hỗ trợ sụn khớp, giảm đau khớp',
    price: 95000,
    image: productImages[28],
    category: 'Thuốc xương khớp',
    stock: 40,
    prescription: false,
  },
  {
    id: '60',
    name: 'MSM 1000mg',
    description: 'Hỗ trợ khớp, giảm viêm',
    price: 78000,
    image: productImages[29],
    category: 'Thuốc xương khớp',
    stock: 35,
    prescription: false,
  },
  {
    id: '61',
    name: 'Salbutamol 100mcg',
    description: 'Thuốc giãn phế quản, điều trị hen suyễn',
    price: 85000,
    image: productImages[0],
    category: 'Thuốc hô hấp',
    stock: 30,
    prescription: true,
  },
  {
    id: '62',
    name: 'Ipratropium 20mcg',
    description: 'Thuốc giãn phế quản, điều trị COPD',
    price: 95000,
    image: productImages[1],
    category: 'Thuốc hô hấp',
    stock: 25,
    prescription: true,
  },
  {
    id: '63',
    name: 'Theophylline 200mg',
    description: 'Thuốc giãn phế quản, điều trị hen suyễn',
    price: 68000,
    image: productImages[2],
    category: 'Thuốc hô hấp',
    stock: 35,
    prescription: true,
  },
  {
    id: '64',
    name: 'Budesonide 200mcg',
    description: 'Thuốc corticoid dạng hít, điều trị hen suyễn',
    price: 120000,
    image: productImages[3],
    category: 'Thuốc hô hấp',
    stock: 20,
    prescription: true,
  },
  {
    id: '65',
    name: 'Fluticasone 250mcg',
    description: 'Thuốc corticoid dạng hít, điều trị hen suyễn',
    price: 150000,
    image: productImages[4],
    category: 'Thuốc hô hấp',
    stock: 15,
    prescription: true,
  },
  {
    id: '66',
    name: 'Coenzyme Q10 100mg',
    description: 'Chống oxy hóa, hỗ trợ tim mạch',
    price: 120000,
    image: productImages[5],
    category: 'Thực phẩm chức năng',
    stock: 30,
    prescription: false,
  },
  {
    id: '67',
    name: 'L-Carnitine 500mg',
    description: 'Hỗ trợ chuyển hóa chất béo, tăng năng lượng',
    price: 95000,
    image: productImages[6],
    category: 'Thực phẩm chức năng',
    stock: 45,
    prescription: false,
  },
  {
    id: '68',
    name: 'Creatine 5g',
    description: 'Hỗ trợ tăng cơ, tăng sức mạnh',
    price: 85000,
    image: productImages[7],
    category: 'Thực phẩm chức năng',
    stock: 50,
    prescription: false,
  },
  {
    id: '69',
    name: 'BCAA 5g',
    description: 'Axit amin chuỗi nhánh, hỗ trợ phục hồi cơ',
    price: 78000,
    image: productImages[8],
    category: 'Thực phẩm chức năng',
    stock: 40,
    prescription: false,
  },
  {
    id: '70',
    name: 'Whey Protein 30g',
    description: 'Protein chất lượng cao, hỗ trợ tăng cơ',
    price: 150000,
    image: productImages[9],
    category: 'Thực phẩm chức năng',
    stock: 35,
    prescription: false,
  },
  {
    id: '71',
    name: 'Casein Protein 30g',
    description: 'Protein giải phóng chậm, hỗ trợ phục hồi ban đêm',
    price: 180000,
    image: productImages[10],
    category: 'Thực phẩm chức năng',
    stock: 25,
    prescription: false,
  },
  {
    id: '72',
    name: 'Collagen 10g',
    description: 'Hỗ trợ da, tóc, móng và khớp',
    price: 120000,
    image: productImages[11],
    category: 'Thực phẩm chức năng',
    stock: 40,
    prescription: false,
  },
  {
    id: '73',
    name: 'Hyaluronic Acid 100mg',
    description: 'Hỗ trợ khớp, làm đẹp da',
    price: 95000,
    image: productImages[12],
    category: 'Thực phẩm chức năng',
    stock: 35,
    prescription: false,
  },
  {
    id: '74',
    name: 'Biotin 5000mcg',
    description: 'Hỗ trợ tóc, móng và da',
    price: 65000,
    image: productImages[13],
    category: 'Thực phẩm chức năng',
    stock: 55,
    prescription: false,
  },
  {
    id: '75',
    name: 'Zinc 50mg',
    description: 'Hỗ trợ miễn dịch, chữa lành vết thương',
    price: 45000,
    image: productImages[14],
    category: 'Thực phẩm chức năng',
    stock: 60,
    prescription: false,
  },
  {
    id: '76',
    name: 'Magnesium 400mg',
    description: 'Hỗ trợ cơ bắp, thần kinh và tim mạch',
    price: 55000,
    image: productImages[15],
    category: 'Thực phẩm chức năng',
    stock: 50,
    prescription: false,
  },
  {
    id: '77',
    name: 'Selenium 200mcg',
    description: 'Chống oxy hóa, hỗ trợ tuyến giáp',
    price: 68000,
    image: productImages[16],
    category: 'Thực phẩm chức năng',
    stock: 40,
    prescription: false,
  },
  {
    id: '78',
    name: 'Chromium 200mcg',
    description: 'Hỗ trợ chuyển hóa đường, kiểm soát cân nặng',
    price: 52000,
    image: productImages[17],
    category: 'Thực phẩm chức năng',
    stock: 45,
    prescription: false,
  },
  {
    id: '79',
    name: 'Manganese 10mg',
    description: 'Hỗ trợ xương, chuyển hóa năng lượng',
    price: 38000,
    image: productImages[18],
    category: 'Thực phẩm chức năng',
    stock: 55,
    prescription: false,
  },
  {
    id: '80',
    name: 'Copper 2mg',
    description: 'Hỗ trợ sắt, collagen và hệ thần kinh',
    price: 42000,
    image: productImages[19],
    category: 'Thực phẩm chức năng',
    stock: 50,
    prescription: false,
  },
  {
    id: '81',
    name: 'Molybdenum 75mcg',
    description: 'Hỗ trợ chuyển hóa protein và axit amin',
    price: 35000,
    image: productImages[20],
    category: 'Thực phẩm chức năng',
    stock: 60,
    prescription: false,
  },
  {
    id: '82',
    name: 'Boron 3mg',
    description: 'Hỗ trợ xương, hormone và não bộ',
    price: 48000,
    image: productImages[21],
    category: 'Thực phẩm chức năng',
    stock: 40,
    prescription: false,
  },
  {
    id: '83',
    name: 'Vanadium 50mcg',
    description: 'Hỗ trợ chuyển hóa đường, kiểm soát cân nặng',
    price: 55000,
    image: productImages[22],
    category: 'Thực phẩm chức năng',
    stock: 35,
    prescription: false,
  },
  {
    id: '84',
    name: 'Silicon 20mg',
    description: 'Hỗ trợ xương, da, tóc và móng',
    price: 62000,
    image: productImages[23],
    category: 'Thực phẩm chức năng',
    stock: 45,
    prescription: false,
  },
  {
    id: '85',
    name: 'Nickel 100mcg',
    description: 'Hỗ trợ chuyển hóa và hấp thu sắt',
    price: 28000,
    image: productImages[24],
    category: 'Thực phẩm chức năng',
    stock: 70,
    prescription: false,
  },
  {
    id: '86',
    name: 'Cobalt 5mcg',
    description: 'Thành phần của vitamin B12',
    price: 32000,
    image: productImages[25],
    category: 'Thực phẩm chức năng',
    stock: 65,
    prescription: false,
  },
  {
    id: '87',
    name: 'Lithium 5mg',
    description: 'Hỗ trợ tâm trạng và sức khỏe tâm thần',
    price: 85000,
    image: productImages[26],
    category: 'Thực phẩm chức năng',
    stock: 25,
    prescription: true,
  },
  {
    id: '88',
    name: 'Strontium 680mg',
    description: 'Hỗ trợ xương, điều trị loãng xương',
    price: 120000,
    image: productImages[27],
    category: 'Thực phẩm chức năng',
    stock: 20,
    prescription: false,
  },
  {
    id: '89',
    name: 'Germanium 100mg',
    description: 'Chống oxy hóa, hỗ trợ miễn dịch',
    price: 95000,
    image: productImages[28],
    category: 'Thực phẩm chức năng',
    stock: 30,
    prescription: false,
  },
  {
    id: '90',
    name: 'Rubidium 5mg',
    description: 'Hỗ trợ hệ thần kinh và tim mạch',
    price: 78000,
    image: productImages[29],
    category: 'Thực phẩm chức năng',
    stock: 35,
    prescription: false,
  },
  {
    id: '91',
    name: 'Cesium 10mg',
    description: 'Hỗ trợ chuyển hóa và năng lượng',
    price: 68000,
    image: productImages[0],
    category: 'Thực phẩm chức năng',
    stock: 40,
    prescription: false,
  },
  {
    id: '92',
    name: 'Barium 5mg',
    description: 'Hỗ trợ hệ tiêu hóa và tim mạch',
    price: 52000,
    image: productImages[1],
    category: 'Thực phẩm chức năng',
    stock: 50,
    prescription: false,
  },
  {
    id: '93',
    name: 'Lanthanum 500mg',
    description: 'Hỗ trợ xương và chuyển hóa photpho',
    price: 150000,
    image: productImages[2],
    category: 'Thực phẩm chức năng',
    stock: 15,
    prescription: false,
  },
  {
    id: '94',
    name: 'Cerium 100mg',
    description: 'Chống oxy hóa, hỗ trợ gan',
    price: 85000,
    image: productImages[3],
    category: 'Thực phẩm chức năng',
    stock: 25,
    prescription: false,
  },
  {
    id: '95',
    name: 'Praseodymium 50mg',
    description: 'Hỗ trợ hệ thần kinh và tim mạch',
    price: 95000,
    image: productImages[4],
    category: 'Thực phẩm chức năng',
    stock: 20,
    prescription: false,
  },
  {
    id: '96',
    name: 'Neodymium 25mg',
    description: 'Hỗ trợ cơ bắp và hệ thần kinh',
    price: 78000,
    image: productImages[5],
    category: 'Thực phẩm chức năng',
    stock: 30,
    prescription: false,
  },
  {
    id: '97',
    name: 'Promethium 10mg',
    description: 'Hỗ trợ chuyển hóa và năng lượng',
    price: 120000,
    image: productImages[6],
    category: 'Thực phẩm chức năng',
    stock: 15,
    prescription: false,
  },
  {
    id: '98',
    name: 'Samarium 20mg',
    description: 'Hỗ trợ xương và hệ miễn dịch',
    price: 98000,
    image: productImages[7],
    category: 'Thực phẩm chức năng',
    stock: 25,
    prescription: false,
  },
  {
    id: '99',
    name: 'Europium 15mg',
    description: 'Hỗ trợ hệ thần kinh và tim mạch',
    price: 110000,
    image: productImages[8],
    category: 'Thực phẩm chức năng',
    stock: 20,
    prescription: false,
  },
  {
    id: '100',
    name: 'Gadolinium 30mg',
    description: 'Hỗ trợ xương và hệ miễn dịch',
    price: 135000,
    image: productImages[9],
    category: 'Thực phẩm chức năng',
    stock: 18,
    prescription: false,
  },
]

export const categories = [
  { name: 'Tất cả', icon: '🏥', count: allProducts.length },
  { name: 'Thuốc giảm đau', icon: '💊', count: allProducts.filter(p => p.category === 'Thuốc giảm đau').length },
  { name: 'Vitamin', icon: '🥗', count: allProducts.filter(p => p.category === 'Vitamin').length },
  { name: 'Thuốc tiêu hóa', icon: '🫀', count: allProducts.filter(p => p.category === 'Thuốc tiêu hóa').length },
  { name: 'Thuốc dị ứng', icon: '🤧', count: allProducts.filter(p => p.category === 'Thuốc dị ứng').length },
  { name: 'Kháng sinh', icon: '🦠', count: allProducts.filter(p => p.category === 'Kháng sinh').length },
  { name: 'Thuốc tiểu đường', icon: '🩸', count: allProducts.filter(p => p.category === 'Thuốc tiểu đường').length },
  { name: 'Thuốc tim mạch', icon: '❤️', count: allProducts.filter(p => p.category === 'Thuốc tim mạch').length },
  { name: 'Thuốc xương khớp', icon: '🦴', count: allProducts.filter(p => p.category === 'Thuốc xương khớp').length },
  { name: 'Thuốc hô hấp', icon: '🫁', count: allProducts.filter(p => p.category === 'Thuốc hô hấp').length },
  { name: 'Thực phẩm chức năng', icon: '💪', count: allProducts.filter(p => p.category === 'Thực phẩm chức năng').length },
]